x-database-env: &database-env
  POSTGRES_DB: payload
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password

services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    # volumes:
    #   - ./apps/server:/app/apps/server
    #   - ./apps/server/node_modules:/app/apps/server/node_modules
    # working_dir: /app/apps/server
    # command: sh -c "pnpm install && pnpm dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    hostname: postgres
    environment:
      <<: *database-env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  node_modules:
  db_data: